### ISSUE TITLE
选一本SOA相关的书

### ISSUE THREAD

**Issue by BaoHongfei** [BaoHongfei/TechWiki#7]
基于dubbo框架下的RPC通讯协议性能测试
http://www.cnblogs.com/lengfo/archive/2015/03/02/4293399.html

http://dubbo.io/Home-zh.htm
http://www.iteye.com/magazines/103#248
http://jm-blog.aliapp.com/?p=3462
https://github.com/alibaba/dubbo-doc-static

**Comment by baohongfei** [comment]
dubbo dubbox
